[package]
name = "jrvor/newprotoype"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.3"
CameraShaker = "encrxyptedethan/camerashaker@1.0.0"
Input = "sleitnick/input@2.3.0"
Trove = "sleitnick/trove@1.5.1"
topbarplus = "1foreverhd/topbarplus@3.3.1"
InstanceCache = "penguindevs/instance-cache@1.0.4"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"